# -*- coding: utf-8 -*-
"""objectdetectionvideo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-8r0A2QSejZB4eOdFBHEEWgP3a_L2Pk
"""

!pip install -q tensorflow
!pip install -q numpy
!pip install -q scipy
!pip install -q numpy
!pip install -q opencv-python
!pip install -q pillow
!pip install -q matplotlib
!pip install -q h5py
!pip install -q keras

!pip install -q imageai-2.0.2-py3-none-any.whl

from imageai.Detection import VideoObjectDetection
import os

execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
detector.loadModel()

video_path = detector.detectObjectsFromVideo(input_file_path=os.path.join( execution_path, "car.mp4"),
                                output_file_path=os.path.join(execution_path, "car_1")
                                , frames_per_second=29, log_progress=True)
print(video_path)